<script setup>
import LecturesTableCom from '@/components/LecturesTableCom.vue';

const lectures = [
    {
        date: "9/12",
        name: "開源茶會",
        speaker: "Willy",
        place: "A3-307",
        tags: ["開源", "迎新"],

        description: "隨著新學期的到來，許多新生已經加入了大同大學這個大家庭，相信大家都迫不及待想要探索和加入感興趣的社團。我們透過舉辦這次茶會，介紹科學開源服務社，幫助你深入了解我們的社團活動和宗旨，並希望你能成為我們大家庭的一員，共同揮灑青春！",
        timeline: [],
        slide: "",
        slido: "",
        handout: "",
        note: "https://hackmd.io/@ttussc/SJP5EjghR/%2FSJp-rjlnA",
        kktix: "https://ttussc.kktix.cc/events/teaparty2024",
    },
    {
        date: "9/19",
        name: "開源是什麼",
        speaker: "Willy",
        place: "A3-200",
        tags: ["開源"],

        description: "",
        timeline: [],
        slide: "",
        slido: "",
        handout: "",
        note: "",
        kktix: "",
    },
    {
        date: "9/26",
        name: "Markdown",
        speaker: "Willy",
        place: "A3-200",
        tags: ["HackMD"],

        description: "",
        timeline: [],
        slide: "",
        slido: "",
        handout: "",
        note: "",
        kktix: "",
    },
    {
        date: "9/30",
        name: "不會被女朋友打的『攝影入門』",
        speaker: "攝影社",
        place: "A3-307",
        tags: ["攝影", "入門"],

        description: "",
        timeline: [],
        slide: "",
        slido: "",
        handout: "",
        note: "",
        kktix: "",
    },
    {
        date: "10/3",
        name: "怕麻煩的話，就Shell出你的指令吧",
        speaker: "芋泥",
        place: "A3-200",
        tags: ["Linux", "Shell"],

        description: "",
        timeline: [],
        slide: "",
        slido: "",
        handout: "",
        note: "",
        kktix: "",
    },
    {
        date: "10/7",
        name: "Re：從 C 開始的大學生活（上）",
        speaker: "阿文",
        place: "A3-200",
        tags: ["C", "程式設計"],

        description: "",
        timeline: [],
        slide: "",
        slido: "",
        handout: "",
        note: "",
        kktix: "",
    },
    {
        date: "10/17",
        name: "Re：從 C 開始的大學生活（下）",
        speaker: "阿文",
        place: "A3-200",
        tags: ["C", "程式設計"],

        description: "",
        timeline: [],
        slide: "",
        slido: "",
        handout: "",
        note: "",
        kktix: "",
    },
    {
        date: "10/21",
        name: "考前讀書會",
        speaker: "Willy",
        place: "A3 8F 樂學空間",
        tags: ["工作坊", "讀書"],

        description: "",
        timeline: [],
        slide: "",
        slido: "",
        handout: "",
        note: "",
        kktix: "",
    },
    {
        date: "11/4",
        name: "E-mail(工作坊)",
        speaker: "神秘講者",
        place: "待定",
        tags: ["工作坊", "Email"],

        description: "",
        timeline: [],
        slide: "",
        slido: "",
        handout: "",
        note: "",
        kktix: "",
    },
    {
        date: "11/7",
        name: "Arduino 基礎介紹",
        speaker: "呆呆、Allen",
        place: "A3-200",
        tags: ["Arduino"],

        description: "",
        timeline: [],
        slide: "",
        slido: "",
        handout: "",
        note: "",
        kktix: "",
    },
    {
        date: "11/14",
        name: "Arduino 無用盒",
        speaker: "呆呆、Allen",
        place: "A3-200",
        tags: ["Arduino", "創客"],

        description: "",
        timeline: [],
        slide: "",
        slido: "",
        handout: "",
        note: "",
        kktix: "",
    },
    {
        date: "11/21",
        name: "Arduino 門禁卡",
        speaker: "呆呆、Allen",
        place: "A3-200",
        tags: ["Arduino", "創客"],

        description: "",
        timeline: [],
        slide: "",
        slido: "",
        handout: "",
        note: "",
        kktix: "",
    },
    {
        date: "11/28",
        name: "作業系統生存指南：Linux 新手的冒險之旅",
        speaker: "小方",
        place: "A3-200",
        tags: ["OS", "Linux"],

        description: "",
        timeline: [],
        slide: "",
        slido: "",
        handout: "",
        note: "",
        kktix: "",
    },
    {
        date: "12/5",
        name: "想學黑魔法嗎？我告訴你有哪些技能",
        speaker: "Timothy",
        place: "A3-307",
        tags: ["資訊安全"],

        description: "",
        timeline: [],
        slide: "",
        slido: "",
        handout: "",
        note: "",
        kktix: "",
    },
    {
        date: "12/12",
        name: "期末大會",
        speaker: "Willy",
        place: "A3-307",
        tags: ["交換禮物"],

        description: "",
        timeline: [],
        slide: "",
        slido: "",
        handout: "",
        note: "",
        kktix: "",
    },
    {
        date: "12/14",
        name: "愛奇兒營隊",
        speaker: "無",
        place: "待定",
        tags: ["服務", "營隊"],

        description: "",
        timeline: [],
        slide: "",
        slido: "",
        handout: "",
        note: "",
        kktix: "",
    },
    {
        date: "12/16",
        name: "考前讀書會",
        speaker: "Willy",
        place: "A3 8F 樂學空間",
        tags: ["工作坊", "讀書"],

        description: "以往學校大考前，社團活動會暫停一次，讓社團的夥伴們專心準備大考。此次與以往不同，希望聚集社團的大家一起召開讀書會，共同為了學校大考而努力。同學與同學之間可以互相照應外，學長姐也可以協助學弟妹考試準備的方向。",
        timeline: [
            "18:00~18:30 入座準備",
            "18:30~20:50 準備考試內容",
            "20:50~21:00 填寫回饋表單",
        ],
        slide: "",
        slido: "",
        handout: "",
        note: "",
        kktix: "",
    },
];

</script>

<template>
    <LecturesTableCom title="2024 上學期 社團課表" :lectures="lectures" />
</template>
