<script setup>
import LecturesTableCom from '@/components/LecturesTableCom.vue';

const lectures = [
    {
        date: "9/12",
        weekday: "四",
        time: "18:00~20:00",
        name: "開源茶會",
        speaker: "威力",
        place: "A3-307",
        tags: ["開源", "迎新"],

        description: "隨著新學期的到來，許多新生已經加入了大同大學這個大家庭，相信大家都迫不及待想要探索和加入感興趣的社團。我們透過舉辦這次茶會，介紹科學開源服務社，幫助你深入了解我們的社團活動和宗旨，並希望你能成為我們大家庭的一員，共同揮灑青春！",
        timeline: [
            "17:30~18:00 場地佈置、進場",
            "18:00~18:30 介紹科學開源服務社",
            "18:30~18:40 各組別與幹部介紹",
            "18:40~19:10 交流與享用茶點",
            "19:10~19:50 桌遊團康活動",
            "19:50~20:00 填寫問卷、收拾場地"
        ],
        slide: "",
        slido: "https://app.sli.do/event/aB84ftRiHDJBgi6CYpcQ31",
        handout: "",
        note: "https://hackmd.io/@ttussc/SJp-rjlnA",
        kktix: "https://ttussc.kktix.cc/events/teaparty2024",
    },
    {
        date: "9/19",
        weekday: "四",
        time: "18:00~20:00",
        name: "開源新手村",
        speaker: "威力",
        place: "A3-200",
        tags: ["開源"],

        description: "在這堂課中，我們將探索開源的核心理念及其對現代科技的影響。課程將介紹開源軟體的基本原則和價值，透過實例展示如何促進創新、協作與學習。我們將討論開源專案對科學研究、軟體開發的影響，並透過 Kahoot！遊戲加深理解。歡迎對開源文化感興趣的同學一同參與！期待能夠凝聚社團的向心力，激勵每位社員積極參與社團活動。",
        timeline: [
            "17:30~18:00：場地佈置、進場",
            "18:00~19:30：介紹開源的基本概念與重要性",
            "19:30~19:50：Kahoot！時間",
            "19:50~20:00：填寫問卷、收拾場地"
        ],
        slide: "",
        slido: "https://app.sli.do/event/3x9JxEntqCz1dXFiZ8KvzB",
        handout: "",
        note: "https://hackmd.io/@ttussc/Bk8ycCF30",
        kktix: "https://ttussc.kktix.cc/events/opensrc113",
    },
    {
        date: "9/26",
        weekday: "四",
        time: "18:00~20:00",
        name: "0 到 1 的社群協作守則",
        speaker: "威力",
        place: "A3-200",
        tags: ["HackMD", "Markdown", "協作"],

        description: "Markdown 是一種輕量級標記語言，適合快速撰寫和編輯格式化文件。本次社課將帶領社員們開啟第一份共筆，讓大家透過實際參與、體驗如何利用 Markdown 進行協作筆記，了解共筆的基本概念與技巧。將教授共筆的訣竅與撰寫方法，並介紹 HackMD 的實用小技巧及常用語法，幫助社員們快速上手，增強協作能力，輕鬆融入本社的共筆文化。",
        timeline: [
            "17:30~18:00 場地佈置、進場",
            "18:00~18:10 開場介紹",
            "18:10~18:40 Markdown 入門基礎教學",
            "19:10~19:50 互動時間 & Kahoot！遊戲",
            "19:50~20:00 填寫問卷、收拾場地",
        ],
        slide: "",
        slido: "https://app.sli.do/event/byfGu55ooLwK3vgu72xTru",
        handout: "",
        note: "https://hackmd.io/@ttussc/ryaAYRF2A",
        kktix: "https://ttussc.kktix.cc/events/markdown113",
    },
    {
        date: "10/3",
        weekday: "四",
        time: "18:00~20:00",
        name: "怕麻煩的話，就Shell出你的指令吧",
        speaker: "芋泥",
        place: "A3-200",
        tags: ["Linux", "Shell"],

        description: "本次活動將透過課程與實作的形式，讓社員們了解 Shell 指令的操作，以及 vim 編輯器的使用指令操作。 首先讓社員們對於 Shell 指令有初步的觀念及一定的了解，再藉由虛擬機讓社員們運用指令去操作檔案，並從實作題中逐步掌握指令的操作。接著帶社員們認識 vim 編輯器與操作指令，最後在實驗中提升掌握度，並且能夠獨立混合運用在一起，希望可以讓社員們在日常電腦操作中獨立使用或深入學習、提升興趣。",
        timeline: [
            "17:30~18:00 場佈、活動準備",
            "18:00~18:30 介紹 Shell 並了解基本指令",
            "18:30~19:30 透過實驗題掌握 Shell 指令操作",
            "19:30~19:50 介紹 vim 並透過實驗題熟悉 vim 指令操作",
            "19:50~20:00 表單回饋"
        ],
        slide: "",
        slido: "https://app.sli.do/event/2fkHawR4KP2NQxFUwzMapN",
        handout: "",
        note: "https://hackmd.io/@ttussc/rkHnYCKnR",
        kktix: "https://ttussc.kktix.cc/events/shell113",
    },
    {
        date: "10/7",
        weekday: "一",
        time: "18:00~20:00",
        name: "Re：從 C 開始的大學生活（上）",
        speaker: "阿文",
        place: "A3-200",
        tags: ["C", "程式設計"],

        description: "從介紹Visual Studio Code、Dev-C++、CodeBlocks 等軟體，建立自己寫程式的開發環境，再進入到基礎的C語言，例如：輸出/入、變數宣告、資料型態、數學、邏輯運算、條件判斷，最後利用問題練習來複習本次課堂的內容。",
        timeline: [
            "17:30~18:00 場佈、活動準備",
            "18:00~18:40 開場閒聊、調查、設置環境",
            "18:40~19:50 正式社課",
            "19:50~20:00 表單回饋",
        ],
        slide: "",
        slido: "https://app.sli.do/event/4TW296oA3oAEFayFQBJsK1",
        handout: "",
        note: "https://hackmd.io/@ttussc/Byxw9CYhC",
        kktix: "https://ttussc.kktix.cc/events/p1clang113",
    },
    {
        date: "10/17",
        weekday: "四",
        time: "18:00~20:00",
        name: "Re：從 C 開始的大學生活（下）",
        speaker: "阿文",
        place: "A3-200",
        tags: ["C", "程式設計"],

        description: "本次社課和上次社課隔了10天，在上新進度前，我們會先複習上次社課的內容，接著在進入比較進階的C語言課程，包含：迴圈、函式、陣列，在過程中會有幾個概念性的問題，加深對本次社課內容的印象。",
        timeline: [
            "17:30~18:00 場佈、活動準備",
            "18:00~18:20 複習上次社課的內容",
            "18:20~19:50 正式社課",
            "19:50~20:00 表單回饋"
        ],
        slide: "",
        slido: "https://app.sli.do/event/fQ6R44hfpgqACyEPtykDiE",
        handout: "",
        note: "https://hackmd.io/@ttussc/SJMd9CKhA",
        kktix: "",
    },
    {
        date: "10/21",
        weekday: "一",
        time: "18:00~20:00",
        name: "考前讀書會",
        speaker: "威力",
        place: "A3 8F 樂學空間",
        tags: ["工作坊", "讀書"],

        description: "以往學校大考前，社團活動會暫停一次，讓社團的夥伴們專心準備大考。此次與以往不同，希望聚集社團的大家一起召開讀書會，共同為了學校大考而努力。同學與同學之間可以互相照應外，學長姐也可以協助學弟妹考試準備的方向。",
        timeline: [],
        slide: "",
        slido: "",
        handout: "",
        note: "",
        kktix: "",
    },
    {
        date: "11/4",
        weekday: "一",
        time: "18:00~20:00",
        name: "E-mail(工作坊)",
        speaker: "神秘講者",
        place: "待定",
        tags: ["工作坊", "Email"],

        description: "",
        timeline: [],
        slide: "",
        slido: "",
        handout: "",
        note: "",
        kktix: "",
    },
    {
        date: "11/7",
        weekday: "四",
        time: "18:00~20:00",
        name: "噹噹噹噹~ Arduino 號要來了",
        speaker: "呆呆、Allen",
        place: "A3-200",
        tags: ["Arduino"],

        description: "Arduino 是將程式邏輯與硬體結合的強大平台。在這次工作坊中，我們將通過簡單的元件，如LED燈控制、蜂鳴器操作、伺服馬達應用，來模擬平交道的運作，幫助社員掌握Arduino的基本操作和應用。這些實驗將加強大家對元件接線的熟練度，並奠定未來專案實作的基礎。不論你是剛接觸Arduino的新手，還是已有經驗的社員，這次活動都將為你提供豐富的學習和交流機會。誠摯邀請對科技與程式設計有興趣的同學共襄盛舉！",
        timeline: [
            "17:30~18:00 場地準備",
            "18:00~18:10 : 註冊帳號並加入課程。",
            "18:10~18:40 : 概述Arduino板的接腳功能，數位與類比的差別，以及基本程式邏輯。",
            "18:40~18:50 LED燈實驗",
            "18:50~19:10 蜂鳴器實驗",
            "19:10~19:30 可變電阻+伺服馬達實驗",
            "19:30~20:00 接合上述三項實驗完成平交道裝置，撰寫程式並進行測試，收集回饋表單。"
        ],
        slide: "",
        slido: "https://app.sli.do/event/nhq5QwZVkfqUmCh8eJVnk9",
        handout: "",
        note: "https://hackmd.io/@ttussc/HkT1sAthR",
        kktix: "",
    },
    {
        date: "11/14",
        weekday: "四",
        time: "18:00~20:00",
        name: "開箱驚喜：Arduino無用盒",
        speaker: "呆呆、Allen",
        place: "A3-200",
        tags: ["Arduino", "創客"],

        description: "程式設計不僅解決問題，也能帶來樂趣。這次社課，我們將程式設計與雷雕技術相結合，將創意和程式碼轉化為實體作品，創造出獨特的有趣盒子。透過實際操作，我們將體驗到如何將抽象的程式邏輯具體化，並在過程中探索科技與藝術的融合。這不僅能讓我們深化對程式設計的理解，也能激發我們的創造力，讓我們的學習變得更加生動與有趣。",
        timeline: [
            "17:30~18:00 : 場地佈置和設備準備",
            "18:00~18:50 無用盒組裝 : 介紹無用盒的組件與功能，進行外框組裝，測試組裝效果，確保無誤。",
            "18:50~19:20 : 複習Arduino板接腳功能，介紹伺服馬達和按鈕，進行接線實作，撰寫並上傳控制程式，調整程式邏輯以符合預期。",
            "19:20~19:50 : 將線路與盒子結合，完成無用盒整體組裝，並進行程式調整。",
            "19:50~20:00 社團回饋與表單填寫"
        ],
        slide: "https://www.canva.com/design/DAGQPFwQnzs/qrJPlJwbXhDrviK7GhcaIg/view?utm_content=DAGQPFwQnzs&utm_campaign=designshare&utm_medium=link&utm_source=editor",
        slido: "https://app.sli.do/event/aRw5Q4mEzvXxuPR7jm8esn",
        handout: "",
        note: "https://hackmd.io/@ttussc/BJRxjCKnA",
        kktix: "",
    },
    {
        date: "11/21",
        weekday: "四",
        time: "18:00~20:00",
        name: "小小Arduino，大大門禁",
        speaker: "呆呆、Allen",
        place: "A3-200",
        tags: ["Arduino", "創客"],

        description: "這次社課將讓我們透過 Arduino 技術，模擬和實現一個門禁卡系統。這不僅有助於提升我們的程式設計和電子工程技能，還能讓我們親身體驗如何將現代科技應用於日常生活中，解決實際問題。通过實際操作，我們將學習如何設計和實作一個簡便而有效的門禁系統，從而更好地理解科技如何影響並改善我們的生活。",
        timeline: [
            "17:30~18:00 : 場地佈置和設備準備",
            "18:00~18:15 : 介紹MFRC522讀卡器及MFRC522.h函式庫，了解其基本功能和應用。",
            "18:15~18:35 : 完成門禁卡的接線工作，包括將MFRC522讀卡器與Arduino板連接，並安裝蜂鳴器和馬達。進行門禁卡的基本測試。",
            "19:00~20:00 : 模擬真實門禁卡系統，進行實際操作和程式講解，並根據需要調整和修改程式。最後收集參與者的回饋意見。"
        ],
        slide: "",
        slido: "https://app.sli.do/event/r9rVfMuVCgudKVqjFAiabt",
        handout: "",
        note: "https://hackmd.io/@ttussc/HktWjRFh0",
        kktix: "",
    },
    {
        date: "11/28",
        weekday: "四",
        time: "18:00~20:00",
        name: "作業系統生存指南",
        speaker: "小方",
        place: "A3-200",
        tags: ["OS", "Linux"],

        description: "本次課程專為初學者設計，旨在讓參與者了解作業系統的基本概念及其在電腦運作中的角色。透過介紹不同的 Linux 發行版本並實作 Arch Linux，參與者將學習如何安裝系統和使用基本指令，深入理解 Linux 系統的運作。期待每位成員的踴躍參與！",
        timeline: [
            "17:30~18:00: 場地佈置、進場",
            "18:00~18:30 介紹作業系統，讓大家對 OS 有一定的概念",
            "18:30~19:00 介紹 Arch Linux 並安裝",
            "19:00~20:00 實際操作 Arch Linux ，介紹 Linux 各發行版的不同"
        ],
        slide: "",
        slido: "https://app.sli.do/event/7E1RBtFZt747zZT9QAEwBZ",
        handout: "",
        note: "https://hackmd.io/@ttussc/rJfGsRtnC",
        kktix: "",
    },
    {
        date: "12/5",
        weekday: "四",
        time: "18:00~20:00",
        name: "想學黑魔法嗎？我告訴你有哪些技能",
        speaker: "Timothy",
        place: "A3-307",
        tags: ["資訊安全"],

        description: "本次活動將以 CTF（Capture The Flag）為主軸，旨在將參與者引入資訊安全的世界。活動開始時，將透過一系列的講解，介紹 CTF 比賽的起源、目的和基本規則，幫助參與者理解 CTF 是如何運作的。接著，我們會逐步介紹 CTF 的六大領域，包括逆向工程、滲透測試、密碼學、取證分析、網絡安全和編碼安全等，讓參與者對每一個領域都有初步的了解，最後帶大家解 CTF 的題目。",
        timeline: [
            "17:30~18:00 布置場地",
            "18:00~19:00 帶大家對資安有初步的認識",
            "19:00~20:00 介紹 CTF 帶大家玩 KAHOOT 題目"
        ],
        slide: "",
        slido: "https://app.sli.do/event/3wCkGTd7kjCPfyh9hXHDzy",
        handout: "",
        note: "https://hackmd.io/@ttussc/Sy2zjAF3C",
        kktix: "",
    },
    {
        date: "12/12",
        weekday: "四",
        time: "18:00~20:00",
        name: "期末大會&聖誕狂歡夜",
        speaker: "威力",
        place: "A3-307",
        tags: ["交換禮物"],

        description: "親愛的社員們，快來參加我們的期末大會暨聖誕派對吧！我們將回顧本學期的精彩瞬間，並在節日氛圍中展開聖誕交換禮物活動，帶來驚喜和歡樂。不僅如此，還有豐富的輕食和飲料等你來享用。這是一場學期總結和節日慶祝的完美結合，別錯過與大家一起歡慶的機會！",
        timeline: [
            "17:30~18:00 場地佈置與進場",
            "18:00~18:50 社團回顧與成果展示",
            "18:50~19:40 聖誕派對",
            "19:50~20:00 填寫問卷、收拾場地"
        ],
        slide: "",
        slido: "https://app.sli.do/event/uknkv6KpkicyQe4ai1Lwhv",
        handout: "",
        note: "https://hackmd.io/@ttussc/HyeSjRtnA",
        kktix: "",
    },
    {
        date: "12/14",
        weekday: "六",
        name: "愛奇兒營隊",
        speaker: "無",
        place: "待定",
        tags: ["服務", "營隊"],

        description: "",
        timeline: [],
        slide: "",
        slido: "",
        handout: "",
        note: "",
        kktix: "",
    },
    {
        date: "12/16",
        weekday: "一",
        time: "18:00~20:00",
        name: "考前讀書會",
        speaker: "威力",
        place: "A3 8F 樂學空間",
        tags: ["工作坊", "讀書"],

        description: "以往學校大考前，社團活動會暫停一次，讓社團的夥伴們專心準備大考。此次與以往不同，希望聚集社團的大家一起召開讀書會，共同為了學校大考而努力。同學與同學之間可以互相照應外，學長姐也可以協助學弟妹考試準備的方向。",
        timeline: [
            "18:00~18:30 入座準備",
            "18:30~20:50 準備考試內容",
            "20:50~21:00 填寫回饋表單",
        ],
        slide: "",
        slido: "",
        handout: "",
        note: "",
        kktix: "",
    },
];

</script>

<template>
    <LecturesTableCom title="2024 上學期 社團課表" :lectures="lectures" />
</template>
